version: '3'

services:
  order-db:
    image: debezium/postgres:11
    volumes:
      - debezium-order-db-data:/var/lib/postgresql/data/
    networks:
      debezium:
        aliases:
          - source-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432

  order:    
    image: puzzle/mm-debezium-order:latest    
    ports:    
      - 8080:8080    
    networks:    
      - debezium
    depends_on:    
      - order-db    
    environment:    
      - QUARKUS_HTTP_PORT=8080    
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://order-db:5432/admin    

  stock-db:
    image: debezium/postgres:11
    volumes:
      - debezium-stock-db-data:/var/lib/postgresql/data/
    networks:
      debezium:
        aliases:
          - stock-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5433:5432

  stock:    
    image: puzzle/mm-debezium-stock:latest    
    ports:    
      - 8081:8080    
    networks:    
      - debezium
    depends_on:
      - stock-db
    environment:
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://stock-db:5432/admin

  zookeeper:
    image: debezium/zookeeper:1.4
    networks:
      - debezium
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: debezium/kafka:1.4
    ports:
     - 9092:9092
    networks:
      - debezium
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  connect:
    image: puzzle/mm-debezium-connect:latest
    ports:
     - 8083:8083
    networks:
      - debezium
    links:
     - kafka
     - order-db
     - stock-db
     - zookeeper
    command: /opt/kafka/kafka_connect_run.sh
    environment:
     - KAFKA_CONNECT_BOOTSTRAP_SERVERS=kafka:9092
     - |
         KAFKA_CONNECT_CONFIGURATION=
         key.converter=org.apache.kafka.connect.json.JsonConverter
         value.converter=org.apache.kafka.connect.json.JsonConverter
         key.converter.schemas.enable=false
         value.converter.schemas.enable=false
         group.id=connect-debezium
         offset.storage.topic=connect-debezium-offsets
         config.storage.topic=connect-debezium-configs
         status.storage.topic=connect-debezium-status
         offset.storage.replication.factor=1
         config.storage.replication.factor=1
         status.storage.replication.factor=1
         consumer.interceptor.classes=io.opentracing.contrib.kafka.TracingConsumerInterceptor
         producer.interceptor.classes=io.opentracing.contrib.kafka.TracingProducerInterceptor
     - KAFKA_CONNECT_METRICS_ENABLED=true
     - STRIMZI_TRACING=jaeger
     - JAEGER_SERVICE_NAME=debezium-connect
     - JAEGER_AGENT_HOST=jaeger

  grafana:
    image: grafana/grafana:7.3.3
    ports:
      - 3000:3000
    networks:
      - debezium
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/dashboards/:/opt/dashboards
      - ./config/grafana/custom.yaml:/etc/grafana/provisioning/dashboards/custom.yaml
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  prometheus:
    image: prom/prometheus:v2.22.2
    ports:
      - 9090:9090
    networks:
      - debezium
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/alert.rules:/etc/prometheus/alert.rules

  alertmanager:
    image: prom/alertmanager:v0.21.0
    ports:
      - 9093:9093
    networks:
      - debezium
    volumes:
      - ./config/alertmanager/alertmanager.yaml:/etc/alertmanager/alertmanager.yml

  jaeger:
    image: jaegertracing/all-in-one:1.21.0
    networks:
      - debezium
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 14268:14268
      - 16686:16686

volumes:
  debezium-order-db-data:
  debezium-stock-db-data:

networks:
  debezium:
    driver: bridge
    ipam:
      driver: default
