version: '3'

services:
  order-db:
    image: debezium/postgres:11
    volumes:
      - debezium-order-db-data:/var/lib/postgresql/data/
    networks:
      kafka:
        aliases:
          - source-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432

  stock-db:
    image: debezium/postgres:11
    volumes:
      - debezium-stock-db-data:/var/lib/postgresql/data/
    networks:
      kafka:
        aliases:
          - stock-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5433:5432

  zookeeper:
    image: debezium/zookeeper:1.4
    networks:
      - kafka
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888

  kafka:
    image: debezium/kafka:1.4
    ports:
     - 9092:9092
    networks:
      - kafka
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  connect:
    image: puzzle/mm-debezium-connect:latest
    ports:
     - 8083:8083
    networks:
      - kafka
    links:
     - kafka
     - order-db
     - stock-db
     - zookeeper
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=connect-debezium
     - CONFIG_STORAGE_TOPIC=connect-debezium-config
     - OFFSET_STORAGE_TOPIC=connect-debezium-offsets
     - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
     - ADVERTISED_HOST_NAME=kafka

  grafana:
    image: grafana/grafana:7.3.3
    ports:
      - 3000:3000
    networks:
      - kafka
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/dashboards/:/opt/dashboards
      - ./config/grafana/custom.yaml:/etc/grafana/provisioning/dashboards/custom.yaml
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  prometheus:
    image: prom/prometheus:v2.22.2
    ports:
      - 9090:9090
    networks:
      - kafka
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/alert.rules:/etc/prometheus/alert.rules

  alertmanager:
    image: prom/alertmanager:v0.21.0
    ports:
      - 9093:9093
    networks:
      - kafka
    volumes:
      - ./config/alertmanager/alertmanager.yaml:/etc/alertmanager/alertmanager.yml

  jaeger:
    image: jaegertracing/all-in-one:1.21.0
    networks:
      - kafka
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 14268:14268
      - 16686:16686

volumes:
  debezium-order-db-data:
  debezium-stock-db-data:

networks:
  kafka:
    driver: bridge
    ipam:
      driver: default
