version: '3'

services:
  lra-coordinator:
    image: jbosstm/lra-coordinator:5.10.6.Final
    hostname: lra-coordinator
    volumes:
      - lra-data:/opt/jboss
    container_name: rest-lra-coordinator
    networks:
      rest:
        aliases:
          - lra-coordinator
    environment:
      - AB_JOLOKIA_OFF="true"
      - THORNTAIL_LOGGING_ROOT-LOGGER.LEVEL=DEBUG
    ports:
      - 8090:8080

  order-db:
    image: postgres:11.9
    hostname: order-db
    container_name: rest-order-db
    volumes:
      - order-db-data:/var/lib/postgresql/data/
    networks:
      rest:
        aliases:
          - order-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432

  order:
    image: puzzle/mm-rest-order:latest
    hostname: order
    container_name: rest-order
    ports:
      - 8080:8080
    networks:
      - rest
    depends_on:
      - order-db
    environment:
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://order-db:5432/admin
      - APPLICATION_ARTICLESTOCK_API_URL=http://stock:8080/
      - APPLICATION_REWRITE_BASE_ENABLED=true
      - APPLICATION_REWRITE_BASE_HOST=order
      - JAVA_TOOL_OPTIONS=-Dlra.http.host=lra-coordinator -Dlra.http.port=8080

  stock-db:
    image: postgres:11.9
    hostname: stock-db
    container_name: rest-stock-db
    volumes:
      - stock-db-data:/var/lib/postgresql/data/
    networks:
      rest:
        aliases:
          - stock-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5433:5432

  stock:
    image: puzzle/mm-rest-stock:latest
    hostname: stock
    container_name: rest-stock
    ports:
      - 8081:8080
    networks:
      - rest
    depends_on:
      - stock-db
    environment:
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://stock-db:5432/admin

  grafana:
    image: grafana/grafana:7.3.3
    container_name: rest-grafana
    ports:
      - 3000:3000
    networks:
      - rest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/dashboards/:/opt/dashboards
      - ./config/grafana/custom.yaml:/etc/grafana/provisioning/dashboards/custom.yaml
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  prometheus:
    image: prom/prometheus:v2.22.2
    container_name: rest-prometheus
    ports:
      - 9090:9090
    networks:
      - rest
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/alert.rules:/etc/prometheus/alert.rules

  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: rest-alertmanager
    ports:
      - 9093:9093
    networks:
      - rest
    volumes:
      - ./config/alertmanager/alertmanager.yaml:/etc/alertmanager/alertmanager.yml

  jaeger:
    image: jaegertracing/all-in-one:1.21.0
    container_name: rest-jaeger
    networks:
      - rest
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 14268:14268
      - 16686:16686

volumes:
  order-db-data:
  stock-db-data:
  lra-data:

networks:
  rest:
    driver: bridge
    ipam:
      driver: default