version: '3'

services:
  monolith-db:
    image: postgres:11.2
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      monolith:
        aliases:
          - monolith-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432

  monolith:
    image: monolith:latest
    ports:
      - 8080:8080
    networks:
      - monolith
    depends_on:
      - monolith-db
    environment:
      - QUARKUS_HTTP_PORT=8080

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - monolith
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/dashboards/:/opt/dashboards
      - ./config/grafana/custom.yaml:/etc/grafana/provisioning/dashboards/custom.yaml
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - monolith
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/alert.rules:/etc/prometheus/alert.rules

  alertmanager:
    image: prom/alertmanager
    networks:
      - monolith
    volumes:
      - ./config/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  jaeger:
    image: jaegertracing/all-in-one
    hostname: jaeger
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 9093:16686